* Overview

This package contains the Matlab source code to convert L1c radiances to L1c radiances with AIRS frequency drifts removed and Doppler shifts removed.  The spectra are shifted to a set of frequencies that are in the variable fl1c.

This package is under git version control (for L. Strow only I imagine).  It can be found at
https://github.com/strow/jpl_nu_cal_packages.git.  I hope to keep this git repo as current as possible to what is used in the JPL operational code, but it will likely diverge...

Note that the test file is not included in the git repo since it is large.

* Directories

** src 

Contains the source code.  

** static

Contains the static data files need for this algorithm.  

** test

Contains the main_pgm.m that shows how to call the frequency calibration main subroutine.  Also included is a L1c test file, and a number of plots of output.  Most of main_pgm.m is just generating these plots, etc.  

The figure outputs are in the Figs directory.  Top level has the Matlab .fig files.  Directory Pdf has the .pdf output (none for 2-d images) and directory Png has the .png outputs.

Testing was done using the L1c file 
  - AIRS.2017.11.09.226.L1C.AIRS_Rad.v6.1.2.0.G17314105227.hdf

* Comments

I plan on doing a day or two of testing in the future.  

The I/O is embedded in the main routine, cal_l1c_freqs_and_doppler.m.  It should be quite easy to pull that into the main program or a subroutine.  Since Matlab can write binary files (or hdf or netcdf), I would suggest (not knowing anything about a NASA DIS PGE) to just run this matlab code from a shell "escape" in the main L1c program before writing out the existing L1c file, then read in the new radiances, and then write out the final L1c file as you do know with modified radiances.  This would minimize the amount of new code that has to be written.  But, no idea if that is possible.
